plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nhatkycaitien.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nhatkycaitien.app'
        minSdk 24
        targetSdk 35
        versionCode 845
        versionName '8.4.5'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
    implementation 'androidx.exifinterface:exifinterface:1.3.7'
}
