package com.nhatkycaitien.app;
import android.content.Context;import android.graphics.*;import android.util.AttributeSet;import android.view.MotionEvent;import android.view.ScaleGestureDetector;import android.view.View;
public class CropImageView extends View{
 private Bitmap bm;private float scale=1,tx=0,ty=0,lastX,lastY;private final Paint p=new Paint(3),shade=new Paint();private ScaleGestureDetector detector;
 public CropImageView(Context c,AttributeSet a){super(c,a);shade.setColor(0x99000000);detector=new ScaleGestureDetector(c,new ScaleGestureDetector.SimpleOnScaleGestureListener(){public boolean onScale(ScaleGestureDetector d){scale*=d.getScaleFactor();scale=Math.max(minScale(),Math.min(scale,8f));clamp();invalidate();return true;}});}
 public void setImage(Bitmap b){bm=b;post(()->{scale=minScale();tx=(getWidth()-bm.getWidth()*scale)/2;ty=(getHeight()-bm.getHeight()*scale)/2;invalidate();});}
 private float box(){return Math.min(getWidth(),getHeight())*.82f;}private float left(){return(getWidth()-box())/2;}private float top(){return(getHeight()-box())/2;}private float minScale(){if(bm==null||getWidth()==0)return 1;return Math.max(box()/bm.getWidth(),box()/bm.getHeight());}
 private void clamp(){if(bm==null)return;float l=left(),t=top(),r=l+box(),b=t+box(),w=bm.getWidth()*scale,h=bm.getHeight()*scale;if(tx>l)tx=l;if(ty>t)ty=t;if(tx+w<r)tx=r-w;if(ty+h<b)ty=b-h;}
 @Override protected void onDraw(Canvas c){super.onDraw(c);c.drawColor(Color.BLACK);if(bm!=null){Matrix m=new Matrix();m.postScale(scale,scale);m.postTranslate(tx,ty);c.drawBitmap(bm,m,p);}float l=left(),t=top(),r=l+box(),b=t+box();c.drawRect(0,0,getWidth(),t,shade);c.drawRect(0,b,getWidth(),getHeight(),shade);c.drawRect(0,t,l,b,shade);c.drawRect(r,t,getWidth(),b,shade);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(Color.WHITE);c.drawRect(l,t,r,b,p);p.setStyle(Paint.Style.FILL);}
 @Override public boolean onTouchEvent(MotionEvent e){detector.onTouchEvent(e);if(e.getPointerCount()==1&&!detector.isInProgress()){if(e.getAction()==MotionEvent.ACTION_DOWN){lastX=e.getX();lastY=e.getY();}else if(e.getAction()==MotionEvent.ACTION_MOVE){tx+=e.getX()-lastX;ty+=e.getY()-lastY;lastX=e.getX();lastY=e.getY();clamp();invalidate();}}return true;}
 public Bitmap crop(int max){clamp();float l=left(),t=top(),s=box();int sx=Math.max(0,Math.round((l-tx)/scale)),sy=Math.max(0,Math.round((t-ty)/scale)),ss=Math.min(Math.round(s/scale),Math.min(bm.getWidth()-sx,bm.getHeight()-sy));Bitmap cut=Bitmap.createBitmap(bm,sx,sy,ss,ss);if(cut.getWidth()>max)return Bitmap.createScaledBitmap(cut,max,max,true);return cut;}
}
