package com.nhatkytimestiming.app;
import android.app.PendingIntent;import android.appwidget.AppWidgetManager;import android.appwidget.AppWidgetProvider;import android.content.*;import android.net.Uri;import android.view.View;import android.widget.RemoteViews;import org.json.*;import java.util.*;
public class ActivityWidgetProvider extends AppWidgetProvider{
 public static final String DATA_PREFS="activity_widget_data",DATA_KEY="activities",CONFIG_PREFS="activity_widget_config";
 public void onUpdate(Context c,AppWidgetManager m,int[] ids){for(int id:ids)update(c,m,id);} public void onEnabled(Context c){refreshAll(c);} public void onReceive(Context c,Intent i){super.onReceive(c,i);String a=i==null?"":i.getAction();if(Intent.ACTION_BOOT_COMPLETED.equals(a)||Intent.ACTION_MY_PACKAGE_REPLACED.equals(a))refreshAll(c);}
 public static void refreshAll(Context c){AppWidgetManager m=AppWidgetManager.getInstance(c);int[] ids=m.getAppWidgetIds(new ComponentName(c,ActivityWidgetProvider.class));for(int id:ids)update(c,m,id);}
 static JSONArray data(Context c){try{return new JSONArray(c.getSharedPreferences(DATA_PREFS,0).getString(DATA_KEY,"[]"));}catch(Exception e){return new JSONArray();}}
 static JSONObject find(JSONArray a,String id){for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null&&id.equals(o.optString("id")))return o;}return null;}
 static PendingIntent activity(Context c,int wid,int slot,String id){Intent i;if(id==null){i=new Intent(c,WidgetConfigActivity.class);i.putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,wid);i.setData(Uri.parse("tracker://config/"+wid+"/"+slot));}else{i=new Intent(c,MainActivity.class);i.putExtra("activity_id",id);i.setData(Uri.parse("tracker://activity/"+wid+"/"+slot+"/"+Uri.encode(id)));}return PendingIntent.getActivity(c,wid*100+slot,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 public static void update(Context c,AppWidgetManager m,int wid){try{RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.widget_activity_grid);JSONArray all=data(c);String raw=c.getSharedPreferences(CONFIG_PREFS,0).getString("selected_"+wid,"[]");JSONArray selected;try{selected=new JSONArray(raw);}catch(Exception e){selected=new JSONArray();}for(int i=1;i<=10;i++){int cell=id(c,"cell"+i),icon=id(c,"icon"+i),name=id(c,"name"+i),run=id(c,"run"+i);JSONObject o=i<=selected.length()?find(all,selected.optString(i-1)):null;if(o==null){v.setTextViewText(icon,"+");v.setTextViewText(name,"");v.setTextViewText(run,"");v.setViewVisibility(cell,View.VISIBLE);v.setOnClickPendingIntent(cell,activity(c,wid,i,null));}else{v.setTextViewText(icon,o.optString("icon","•"));v.setTextViewText(name,o.optString("name",""));boolean running=o.optBoolean("running",false)&&"timing".equals(o.optString("mode"));if(running){long started=parseTime(o.optString("startedAt",""));long elapsed=Math.max(0L,System.currentTimeMillis()-started);v.setViewVisibility(run,View.VISIBLE);v.setTextViewText(run,formatElapsed(elapsed));}else{v.setTextViewText(run,"");v.setViewVisibility(run,View.GONE);}v.setOnClickPendingIntent(cell,activity(c,wid,i,o.optString("id")));}}m.updateAppWidget(wid,v);}catch(Exception error){RemoteViews fallback=new RemoteViews(c.getPackageName(),R.layout.widget_activity_grid);for(int i=1;i<=10;i++){int icon=id(c,"icon"+i),name=id(c,"name"+i),run=id(c,"run"+i),cell=id(c,"cell"+i);fallback.setTextViewText(icon,"+");fallback.setTextViewText(name,"");fallback.setTextViewText(run,"");fallback.setViewVisibility(run,View.GONE);fallback.setOnClickPendingIntent(cell,activity(c,wid,i,null));}m.updateAppWidget(wid,fallback);}}
 static long parseTime(String value){if(value==null||value.isEmpty())return System.currentTimeMillis();String[] patterns={"yyyy-MM-dd'T'HH:mm:ss.SSSXXX","yyyy-MM-dd'T'HH:mm:ssXXX","yyyy-MM-dd'T'HH:mm:ss.SSS","yyyy-MM-dd'T'HH:mm:ss","yyyy-MM-dd'T'HH:mm"};for(String pattern:patterns){try{java.text.SimpleDateFormat f=new java.text.SimpleDateFormat(pattern,java.util.Locale.US);f.setLenient(false);return f.parse(value).getTime();}catch(Exception ignored){}}return System.currentTimeMillis();}
 static String formatElapsed(long ms){long total=Math.max(0L,ms)/1000L,h=total/3600L,m=(total%3600L)/60L,s=total%60L;return h>0?String.format(java.util.Locale.US,"%d:%02d:%02d",h,m,s):String.format(java.util.Locale.US,"%02d:%02d",m,s);}
 static int id(Context c,String n){return c.getResources().getIdentifier(n,"id",c.getPackageName());}
}
