package com.nhatkytimestiming.app;
import android.app.Activity;import android.appwidget.AppWidgetManager;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;
public class WidgetConfigActivity extends Activity{
 int wid=AppWidgetManager.INVALID_APPWIDGET_ID; final ArrayList<String> selected=new ArrayList<>(); TextView count; LinearLayout list;
 public void onCreate(Bundle b){super.onCreate(b);setResult(RESULT_CANCELED);wid=getIntent().getIntExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,wid);if(wid==AppWidgetManager.INVALID_APPWIDGET_ID){finish();return;}build();load();}
 TextView text(String t,int sp){TextView v=new TextView(this);v.setText(t);v.setTextSize(sp);v.setTextColor(Color.rgb(55,24,32));v.setPadding(16,12,16,12);return v;}
 void build(){ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,20,20,30);root.setBackgroundColor(Color.rgb(255,248,230));TextView title=text("Chọn hoạt động cho widget",22);title.setTypeface(null,1);root.addView(title);count=text("0 / 10",15);root.addView(count);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);Button save=new Button(this);save.setText("Lưu widget");save.setOnClickListener(v->save());root.addView(save);scroll.addView(root);setContentView(scroll);}
 void load(){JSONArray a=ActivityWidgetProvider.data(this);String old=getSharedPreferences(ActivityWidgetProvider.CONFIG_PREFS,0).getString("selected_"+wid,"[]");try{JSONArray x=new JSONArray(old);for(int i=0;i<x.length();i++)selected.add(x.optString(i));}catch(Exception ignored){}for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;String id=o.optString("id"),label=o.optString("icon","•")+"  "+o.optString("name")+"  · "+("timing".equals(o.optString("mode"))?"Timing":"Times");CheckBox cb=new CheckBox(this);cb.setText(label);cb.setTextSize(15);cb.setPadding(8,8,8,8);cb.setChecked(selected.contains(id));cb.setOnCheckedChangeListener((b,on)->{if(on){if(selected.size()>=10){b.setChecked(false);Toast.makeText(this,"Tối đa 10 hoạt động",Toast.LENGTH_SHORT).show();return;}selected.add(id);}else selected.remove(id);refresh();});list.addView(cb);}refresh();}
 void refresh(){count.setText(selected.size()+" / 10");}
 void save(){JSONArray a=new JSONArray();for(String id:selected)a.put(id);getSharedPreferences(ActivityWidgetProvider.CONFIG_PREFS,0).edit().putString("selected_"+wid,a.toString()).commit();ActivityWidgetProvider.update(this,AppWidgetManager.getInstance(this),wid);Intent r=new Intent();r.putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,wid);setResult(RESULT_OK,r);finish();}
}
